Add Zh3nNode to Finality Provider
babylonchain/networks pull request #211
Opened 2024-05-28 04:17 UTC by evgeniaverkin

2024-05-28 10:10 UTC, vitsalis requested changes

2024-05-28 10:10 UTC, vitsalis commented on bbn-test-4/finality-providers/registry/Zh3nNode.json
> +  "commission": ".05",
Please use a full commission, i.e. `0.05`

2024-05-29 07:50 UTC, filippos47 approved these changes
Thanks team!

2024-05-29 07:53 UTC, vitsalis approved these changes

2024-05-29 07:53 UTC, merged